### ISSUE TITLE
Breaks when used with hot module replacement

### ISSUE THREAD

**Issue by kalley** [dcousineau/force-case-sensitivity-webpack-plugin#2]
[Hot Module Replacement](https://webpack.github.io/docs/webpack-dev-server.html#hot-module-replacement) adds entries to the config, which then leads to getting the following error:

``` programming
.../node_modules/force-case-sensitivity-webpack-plugin/index.js:26
        if (files.indexOf(resourceName) === -1) {
                 ^
TypeError: Cannot read property 'indexOf' of undefined
    at .../node_modules/force-case-sensitivity-webpack-plugin/index.js:26:18
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Where `resourceName` ends up being `localhost:8080` and `parentDir` ends up `.../node_modules/webpack-dev-server/client/index.js?http:/'`

**Comment by dcousineau** [comment]
Fixed in 0.2.0
