### ISSUE TITLE
please publish v0.1.1 to npm

### ISSUE THREAD

**Issue by olslash** [dcousineau/force-case-sensitivity-webpack-plugin#4]
thanks!

**Comment by graingert** [comment]
@dcousineau is this package still alive?

**Comment by graingert** [comment]
@olslash you can use force-case-sensitivity-webpack-plugin2@0.1.1 in the meantime

**Comment by dcousineau** [comment]
@graingert @olslash I keep forgetting about it, I've published 0.2.0 just now
